### ISSUE TITLE
Broadway Support

### ISSUE THREAD

**Issue by TheOPtimal** [udevbe/greenfield#120]
GDK is the underlying rendering library behind GTK. It provides multiple backends including X11, Wayland, Quartz (macOS) and GDI (Windows). But there's also another one called Broadway that is of interest here - Broadway renders to a browser. Instead of a canvas or WebGL, Broadway uses the standard DOM.

To try it, run

```bash
gtk4-broadwayd :5
GDK_BACKEND=broadway BROADWAY_DISPLAY=:5 gtk4-demo
```

And then open http://127.0.0.1:8085 in your web browser. It works quite well, but it can be a bit buggy at times.

My point is - It would be nice to have a broadway server integrated into Greenfield as it could offer better performance than going through Wayland.

**Comment by Zubnix** [comment]
Unfortunately that would be technologically extremely hard to do and would only benefit GTK.

Hard to do because it outputs DOM whereas Greenfield paints to a HTML Canvas (which additionally can't paint from HTML). Greenfield *could* drop HTML Canvas painting but performance would suffer, and atomic scene updates would also be gone (there was a point in Greenfield's history where it would paint to DOM actually).
